### ISSUE TITLE
column summaries don't appear when clicked 

### ISSUE THREAD

**Issue by yochannah** [intermine/im-tables#196]
Clicking the column summary icon (small bar chart) at the top of each column should open up a small modal. it doesn't. 

This is the error in the console: `TypeError: Model is not a constructor`

**Comment by uosl** [comment]
I tried converting `CoreModel` to use `Backbone.Model.extend` instead of ES6 class syntax, but no difference. I also tried using `Backbone.Model` directly, in which case I think it fails before the original error.

My main suspicion is that `this.Model` is being changed to something that isn't a class, but I'm unable to find where this is being done.

**Comment by uosl** [comment]
I managed to make *progress* by editing `src/views/facets/facet-view.js:56`
```javascript
    Model() { return new SummaryItems({query: this.query, view: this.view}); }
```
to be a regular function inside `initClass`.
```javascript
      const self = this;
      this.prototype.Model = function() {
        return new SummaryItems({query: self.prototype.query, view: self.prototype.view});
      }
```

This gives a new error about `query` being undefined. I have not been able to figure out how `query` gets defined though.
